### ISSUE TITLE
Crash after connection

### ISSUE THREAD

**Issue by gabrc52** [SixDigitCode/AirBridge#1]
After I try to connect, it crashes:

```
[Verb] [SMServerAPI.js] [authenticate] Authenticating to SMServer
[Info] [SMServerWebsocket.js] [SMServerWebsocket.js] Started listening to websocket
(node:12221) Warning: N-API is an experimental feature and could change at any time.
[Info] [index.js] [index.js] server listening to {"address":"::","family":"IPv6","port":1359}
[Verb] [SMServerAPI.js] [SMServerFetch] Making request to /requests?password=[redacted]
[Verb] [SMServerAPI.js] [SMServerFetch] Request finished successfully, parsing...
[Info] [SMServerWebsocket.js] [SMServerWebsocket.js] Trying to reconnect to websocket...
[ Ok ] [SMServerWebsocket.js] [SMServerWebsocket.js] SMServer WebSocket Client Connected
[Info] [Client.js] [Client] new client connection from ::ffff:[redacted]:48502
[Info] [Client.js] [setupTransmissionCheck] Setting up transmission check
[Verb] [Client.js] [setupTransmissionCheck] Transmission check: de7d244df61e3b81af6f0bfb9ea3dc7f30c13f2333657aba386d5c5ab4273d56
net.js:714
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:714:11)
    at new Client (/home/rgabriel/AirBridge/Client.js:1810:25)
    at Server.handleConnection (/home/rgabriel/AirBridge/index.js:21:22)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at TCP.onconnection (net.js:1577:8)
```

**Comment by gabrc52** [comment]
Nvm my version of NodeJS was too outdated. I upgraded from v8 to v16 and the error no longer occurs.

https://stackoverflow.com/a/64235873
